source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

pod 'VTMagic', '~> 1.2.3'
pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'YYModel', '~> 1.0.4'
pod 'MJRefresh', '~> 3.1.10'
pod 'SDWebImage', '~> 3.8.1'
pod 'HMSegmentedControl', '~> 1.5.2'
pod 'DOPDropDownMenu', '~> 0.1.1'
pod 'pop', '~> 1.0.9'
pod 'Masonry', '~> 1.0.1'